name: Snapcrft linux test

on: push

jobs:
  my-job:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      # You can now run Snapcraft shell commands

      - name: Use Snapcraft - show help
        run: snapcraft --help

      # - name: Use Snapcraft - actually build a snap
      #   run: |
      #     time snapcraft --debug
      #     ls -l
      #     unsquashfs -l *.snap

      - name: Install Snapcraft with LXD - rather than multipass
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
      - name: Build snap
        run: |
          sg lxd -c 'snapcraft --use-lxd'
          ls -l
          # unsquashfs -l *.snap

      - name: Zip it up
        # run: zip -r rubber_band_async.zip dist/
        run: zip mysnap.zip *.snap
      - name: Save it as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: mysnap_artifact.zip
          path: mysnap.zip
