name: Rubberband wxpython linux and mac 
on:
  push:
    branches: [ main ]
jobs:
  buildfun:
    # runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-18.04, windows-latest]
        # os: [macos-latest, ubuntu-18.04, ubuntu-20.04]
        os: [macos-latest]

    # job level env attempt
    env:
      MY_ENV_1: My environment variable 1
      MY_ENV_2: My environment variable 2

    steps:
    - name: Set env var 3.9
      # this seems to only affect this step. Whilst job wide env setting is possible, not sure how to do that
      env:
          PY_VERS: 3.9
      run: echo "we just set env.PY_VERS to ${{ env.PY_VERS }}"

    - name: Set env var 3.9 using technique 2
      run: echo "PYTHON_VERSION=3.7" >> $GITHUB_ENV
    - name: Report env using technique 2
      run: echo "PYTHON_VERSION is ${{ env.PYTHON_VERSION }} aka $PYTHON_VERSION"

    - name: Report env
      run: |
        echo "PY_VERS is ${{ env.PY_VERS }} aka $PY_VERS"
        echo "PYTHON_VERSION is ${{ env.PYTHON_VERSION }} aka $PYTHON_VERSION"
        echo $MY_ENV_1, $MY_ENV_2

    - uses: actions/checkout@v2       
    - name: Setup Python please
      uses: actions/setup-python@v2
      with:
        # python-version: 3.9    
        python-version: 3.8 
        # python-version: ${{ env.PY_VERS }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

        echo "$RUNNER_OS"
        echo "${{ matrix.os }}"
        if [ "$RUNNER_OS" == "Linux" ]; then    # report linux distro version
          lsb_release -a 
        fi
        echo "Ideally using Python $PY_VERS"
        echo "Ideally PYTHON_VERSION is ${{ env.PYTHON_VERSION }} aka $PYTHON_VERSION"

        if [ "$RUNNER_OS" == "Linux" ]; then
          pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/${{ matrix.os }} wxPython
          sudo apt-get install libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

        elif [ "$RUNNER_OS" == "macOS" ]; then
          pip install wxpython

        elif [ "$RUNNER_OS" == "Windows" ]; then
            # choco install important_windows_software
            echo "windows - TODO"

        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi

        pip install -r requirements.txt
        pip install pyinstaller

    - name: Report Python version_info
      run: |
        python -c "import sys; print(sys.version_info)"
        uname -a

    - name: Build executable using Pyinstaller
      run: |
        # pyinstaller --windowed -F --noconfirm -i icons/Dakirby309-Simply-Styled-Mac-Front-Row.icns rubber_band_async.py
        pyinstaller rubber_band_async_custom.spec
        ls -l dist/

    # No need to zip it up since Github Actions auto zips artifacts when they are downloaded, and there
    # is no way around that https://github.com/actions/upload-artifact/issues/39 
    # 
    # - name: Zip up dist/
    #   # run: zip -r dist.zip dist/rubber_band_async.app
    #   # run: zip -r dist.zip dist/rubber_band_async
    #   run: zip -r dist-${{ matrix.os }}.zip dist/

    - name: Save generated executable file as an artifact
      uses: actions/upload-artifact@v2
      with:
        # name: rubber-band-${{ matrix.os }}.zip
        name: rubber-band-${{ matrix.os }}
        path: dist/
