name: Basic deps test of wxpython linux 18.04 dependency
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2       
    - name: Setup Python please
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements-linux-18.04.txt
        pip install pyinstaller
    - name: Run Python say hi
      run: python -c "print('hi')"
    - name: Run example app
      run: python example_app.py
    - name: Run Pyinstaller
      run: |
        pyinstaller example_app.py
        ls -l dist/example_app/ 
        dist/example_app/example_app
    - name: Zip it up baby
      run: zip -r example_app.zip dist/*
    - name: Save it as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: example_app_artifact.zip
        path: example_app.zip